#!/bin/bash

/usr/bin/printf "Creating ACD mount target\n"
/bin/mkdir -p /mnt/.acd

/usr/bin/printf "Syncing with ACD\n"
/usr/local/bin/acd_cli sync

/bin/fdmove 1 3 /usr/bin/printf "Mounting ACD\n"
/usr/local/bin/acd_cli mount -fg -ao -i 900 /mnt/.acd
